name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: AI Code Review
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for git diff against base branch

      # ── Install agent ──────────────────────────────────────────────────────
      - name: Install agent
        run: |
          curl -sSL https://github.com/bitop-dev/agent/releases/latest/download/agent_latest_linux_amd64.tar.gz \
            | tar -xz && sudo mv agent /usr/local/bin/agent

      # ── Write config ───────────────────────────────────────────────────────
      - name: Write config
        run: |
          cat > /tmp/agent.yaml << 'EOF'
          provider: anthropic
          model: claude-sonnet-4-5
          api_key: ${ANTHROPIC_API_KEY}
          max_tokens: 4096
          max_turns: 10
          auto_approve: true
          tools:
            preset: readonly
            work_dir: .
          EOF

      # ── Compute diff ───────────────────────────────────────────────────────
      - name: Get PR diff
        id: diff
        run: |
          git diff origin/${{ github.base_ref }}...HEAD \
            -- '*.go' '*.md' '*.yaml' '*.yml' \
            > /tmp/pr.diff

          LINES=$(wc -l < /tmp/pr.diff)
          echo "lines=$LINES" >> $GITHUB_OUTPUT
          echo "PR diff: $LINES lines"

      # ── Skip if diff is empty ──────────────────────────────────────────────
      - name: Skip if no diff
        if: steps.diff.outputs.lines == '0'
        run: echo "No relevant changes — skipping AI review"

      # ── Run review ─────────────────────────────────────────────────────────
      - name: Run AI review
        if: steps.diff.outputs.lines != '0'
        id: review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          REVIEW=$(agent -config /tmp/agent.yaml -prompt "
          Review this pull request diff. Focus on:
          - Correctness and logic errors
          - Security vulnerabilities or unsafe patterns
          - Missing or inadequate error handling
          - Test coverage gaps for new code
          - API or interface breaking changes
          - Performance concerns

          Be concise. Use bullet points. Group findings by file.
          If the changes look good, say: ✅ LGTM — no significant issues found.

          Diff:
          $(cat /tmp/pr.diff)
          ")

          # Write to file to avoid GitHub output size limits
          echo "$REVIEW" > /tmp/review.txt
          echo "Review complete ($(wc -l < /tmp/review.txt) lines)"

      # ── Post review comment ─────────────────────────────────────────────────
      - name: Post review comment
        if: steps.diff.outputs.lines != '0'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('/tmp/review.txt', 'utf8');

            // Delete previous bot review comments to avoid duplicates
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            for (const c of comments.data) {
              if (c.user.type === 'Bot' && c.body.startsWith('## 🤖 AI Code Review')) {
                await github.rest.issues.deleteComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: c.id,
                });
              }
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## 🤖 AI Code Review\n\n${review}\n\n---\n_Generated by [bitop-dev/agent](https://github.com/bitop-dev/agent)_`,
            });
